package com.erstegroup.lio.db.model;
// Generated Oct 26, 2017 2:20:04 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.erstegroup.lio.constants.DAOConstants;

/**
 * SchedulerJobGroup generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "scheduler_job_group", schema = "scheduler_db", uniqueConstraints = @UniqueConstraint(columnNames = "sch_job_group_name"))
public class SchedulerJobGroup implements java.io.Serializable {

	private long schJobGroupId;
	private String schJobGroupName;
	private String createdBy;
	private Date createdOn;
	private Date deletedOn;
	private String deletedBy;

	public SchedulerJobGroup() {
	}

	public SchedulerJobGroup(long schJobGroupId, String schJobGroupName, String createdBy, Date createdOn) {
		this.schJobGroupId = schJobGroupId;
		this.schJobGroupName = schJobGroupName;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
	}

	public SchedulerJobGroup(long schJobGroupId, String schJobGroupName, String createdBy, Date createdOn,
			Date deletedOn, String deletedBy) {
		this.schJobGroupId = schJobGroupId;
		this.schJobGroupName = schJobGroupName;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.deletedOn = deletedOn;
		this.deletedBy = deletedBy;
	}

	@Id
	@Column(name = "sch_job_group_id", unique = true, nullable = false)
	@SequenceGenerator(allocationSize=1, schema = DAOConstants.SCHEDULER_DB , sequenceName=DAOConstants.SCH_JOB_GROUP_ID_SEQ, name=DAOConstants.SCH_JOB_GROUP_ID_SEQ_NAME)
	@GeneratedValue(strategy=GenerationType.SEQUENCE , generator = DAOConstants.SCH_JOB_GROUP_ID_SEQ_NAME)
	public long getSchJobGroupId() {
		return this.schJobGroupId;
	}

	public void setSchJobGroupId(long schJobGroupId) {
		this.schJobGroupId = schJobGroupId;
	}

	@Column(name = "sch_job_group_name", unique = true, nullable = false)
	public String getSchJobGroupName() {
		return this.schJobGroupName;
	}

	public void setSchJobGroupName(String schJobGroupName) {
		this.schJobGroupName = schJobGroupName;
	}

	@Column(name = "created_by", nullable = false)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", nullable = false, length = 29)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_on", length = 29)
	public Date getDeletedOn() {
		return this.deletedOn;
	}

	public void setDeletedOn(Date deletedOn) {
		this.deletedOn = deletedOn;
	}

	@Column(name = "deleted_by")
	public String getDeletedBy() {
		return this.deletedBy;
	}

	public void setDeletedBy(String deletedBy) {
		this.deletedBy = deletedBy;
	}

}
