package com.erstegroup.lio.db.model;
// Generated Oct 21, 2017 4:18:21 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserLogin generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "user_login", schema = "scheduler_db")
public class UserLogin implements java.io.Serializable {

	private String ulUserName;
	private String ulPassword;
	private Boolean ulEnabled;
	private String ulRole;
	private String ulUserFullName;

	public UserLogin() {
	}

	public UserLogin(String ulUserName) {
		this.ulUserName = ulUserName;
	}

	public UserLogin(String ulUserName, String ulPassword, Boolean ulEnabled, String ulRole, String ulUserFullName) {
		this.ulUserName = ulUserName;
		this.ulPassword = ulPassword;
		this.ulEnabled = ulEnabled;
		this.ulRole = ulRole;
		this.ulUserFullName = ulUserFullName;
	}

	@Id
	@Column(name = "ul_user_name", unique = true, nullable = false)
	public String getUlUserName() {
		return this.ulUserName;
	}

	public void setUlUserName(String ulUserName) {
		this.ulUserName = ulUserName;
	}

	@Column(name = "ul_password")
	public String getUlPassword() {
		return this.ulPassword;
	}

	public void setUlPassword(String ulPassword) {
		this.ulPassword = ulPassword;
	}

	@Column(name = "ul_enabled")
	public Boolean getUlEnabled() {
		return this.ulEnabled;
	}

	public void setUlEnabled(Boolean ulEnabled) {
		this.ulEnabled = ulEnabled;
	}

	@Column(name = "ul_role")
	public String getUlRole() {
		return this.ulRole;
	}

	public void setUlRole(String ulRole) {
		this.ulRole = ulRole;
	}
	
	@Column(name = "ul_user_full_name")
	public String getUlUserFullName() {
		return this.ulUserFullName;
	}

	public void setUlUserFullName(String ulUserFullName) {
		this.ulUserFullName = ulUserFullName;
	}

}
